### ISSUE TITLE
vector.so: undefined symbol: _xgetbv

### ISSUE THREAD

**Issue by pgloader** [pgvector/pgvector#558] opened 2024-05-14 18:06 UTC
postgres=# CREATE EXTENSION vector;
ERROR:  could not load library "/var/opt/icetools/postgres/postgresql.15.3.0.3/15.3/lib/postgresql/vector.so": /var/opt/icetools/postgres/postgresql.15.3.0.3/15.3/lib/postgresql/vector.so: undefined symbol: _xgetbv

How to resolve it ?

**Comment by ankane** [comment] 2024-05-14 19:15
Hi @pgloader, this looks like a duplicate of #538. Which compiler (including the version) did you use to compile the extension?

**Comment by pgloader** [comment] 2024-05-14 20:08
[postgres@m4s-poc-zzmwdb-01 /home/postgres]$ gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by pgloader** [comment] 2024-05-14 20:11
it works after PG_CFLAGS="-DDISABLE_DISPATCH" make

**Comment by pgloader** [comment] 2024-05-14 20:11
What's the impact of DISABLE_DISPATCH  ?

**Closed** 2024-05-15 16:04 UTC
