### ISSUE TITLE
Query returns indexed rows with noticeable "steps"; how to control?

### ISSUE THREAD

**Issue by kinghuang** [pgvector/pgvector#687] opened 2024-09-30 23:55 UTC
I have pgvector 0.7.2 installed and using hnsw indexes on several tables. Given a `hnsw.ef_search` value like 200, I've noticed that rows come back in noticeable "steps". That is, I get the first 6 rows almost right away, then another 25 rows 2 seconds later, then another 125 rows 8 seconds later, before finally reaching 200.

What causes the rows to be returned in such a pattern? Is it something I can control or optimize for? I've tried fiddling with `hnsw.ef_search` in queries and the `m` and `ef_construction` parameters in indexes, but I always get the bumps at 6, 25, 125, etc.

Edit: The return pattern actually appears to be 1, 5, 25, 125, …. The time between the first row and the next five is miniscule. Didn't notice it at first.

**Comment by ankane** [comment] 2024-10-01 00:15
Hi @kinghuang, what's the output of `EXPLAIN ANALYZE`?

**Comment by kinghuang** [comment] 2024-10-01 00:50
This is with `hnsw.ef_search = 200`.

```sql
select
  e.doc_id,
  e.ext_id,
  e.source_id,
  e.reference_datetime,
  cs.dist as cs_dist

from dlph_doc__embedding_4 e
cross join lateral (
  select embedding <=> dlph__ml.vertexai_embedding('example')::vector(768) dist
) cs

order by cs.dist;
```

```
Index Scan using dlph_doc__embedding_4_embedding_idx on dlph_doc__embedding_4 e  (cost=27.01..11700.84 rows=38162 width=36) (actual time=152.395..12480.575 rows=207 loops=1)
  Order By: (embedding <=> (dlph__ml.vertexai_embedding('example'::text, 'text-embedding-004'::text))::vector(768))
Planning Time: 0.129 ms
Execution Time: 12480.767 ms
```

**Comment by ankane** [comment] 2024-10-01 01:32
Are you using a hosted Postgres service?

**Comment by kinghuang** [comment] 2024-10-01 01:38
Yeah, I'm on Crunchy Bridge by Crunchy Data.

**Comment by ankane** [comment] 2024-10-01 01:50
Hmm, pgvector currently gets all rows from the index before the first one is returned, so I don't think the issue is there. Also, I'm not able to get that query to use an index when testing locally with Postgres 16 (even with `enable_seqscan = off`).

If you pass a vector instead of a function call, does it still happen? If not, I'd see if `vertexai_embedding` is marked as `VOLATILE` (the default).

**Comment by ankane** [comment] 2024-10-01 02:56
It looks like this is due to how the query is written and the function being `STABLE` (as it doesn't happen with `IMMUTABLE` and `VOLATILE` won't use the index).

```sql
CREATE OR REPLACE FUNCTION embed(t text) RETURNS vector AS $$
    BEGIN
        RAISE NOTICE 'embed: %', t;
        RETURN '[3,1,2]';
    END;
$$ LANGUAGE plpgsql STABLE;

CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(3));
CREATE INDEX ON items USING hnsw (embedding vector_cosine_ops);
INSERT INTO items (embedding) VALUES ('[1,2,3]'), ('[4,5,6]'), ('[7,8,9]');

SET enable_seqscan = off;
EXPLAIN ANALYZE SELECT * FROM items CROSS JOIN LATERAL (SELECT embedding <=> embed('text')::vector(3) dist) cs ORDER BY dist;
```

This will call the function (and print `embed: text`) 4 times - once for the initial query and then for each result.

If you change how the query is written, it'll only call the function once.

```sql
EXPLAIN ANALYZE SELECT * FROM items ORDER BY embedding <=> (SELECT embed('text')::vector(3)) LIMIT 5;
```

Also, I'd recommend adding `LIMIT` to the query (rather than relying on `ef_search` to limit results).

**Closed by ankane** 2024-10-01 02:56 UTC
