### ISSUE TITLE
Block locking in HNSW scans & races with VACUUM

### ISSUE THREAD

**Issue by MMeent** [pgvector/pgvector#256] opened 2023-09-07 08:59 UTC
In HNSW scans, you re-lock the index page that is supposed to contain the to-be-returned index tuple:

https://github.com/pgvector/pgvector/blob/master/src/hnswscan.c#L211-L217

It references the PostgreSQL documentation on [Index Locking](https://www.postgresql.org/docs/current/index-locking.html), which explains that this additional locking is to prevent snapshots with `SnapshotAny` rules from returning invalid results.

It seems to me that the HNSW index doesn't check that this index tuple is still on the index page it locks, and thus doesn't actually prevent the issue that the comment refers to.

**Comment by ankane** [comment] 2023-09-07 19:19
Hi @MMeent, the full vacuum strategy should guarantee the tuple is still on the index page (a tuple that is about to be marked as deleted won't show up in index scans), but feel free to share if you can reproduce with code.

**Closed by ankane** 2023-09-07 19:19 UTC

**Comment by ankane** [comment] 2023-09-07 20:36
Vacuum [won't complete](https://github.com/pgvector/pgvector/blob/8fa90014743b06acfa27432a355f9521242286c4/src/hnswvacuum.c#L446-L448) when there are index scans in-progress, so the scenario above isn't possible.

**Comment by ankane** [comment] 2023-09-07 21:13
My bad, it looks like that only covers part of the scan. Pushed a fix to the [hnsw-locking](https://github.com/pgvector/pgvector/compare/hnsw-locking) branch.
