### ISSUE TITLE
Inconsistent Semantic Result 

### ISSUE THREAD

**Issue by lovanto** [pgvector/pgvector#616] opened 2024-07-05 08:01 UTC
Hi all, as a newcomer to this field. I've encountered inconsistent results in semantic search despite using the same embedding on pgvector. It appears that the search outcomes vary unexpectedly, which affects the reliability of the system. I have verified that the embeddings are consistent, yet the retrieved results show discrepancies, indicating a potential issue with the semantic search algorithm or configuration. Further investigation is needed to identify and resolve the root cause of this inconsistency.

````
SELECT id,...,embedding <-> '[${parameter}]' AS rank FROM table_name
WHERE condition 1
AND condition 2
AND condition 3
ORDER BY rank ASC 
LIMIT 10
````

**Actual Result**
Every iteration return the different result.

**Expected Result** 
The same data will be return each iteration.

**Comment by jkatz** [comment] 2024-07-07 18:57
@lovanto When debugging, can you run `EXPLAIN ANALYZE` to see if the same query plan is selected? If it is the same query plan and it's using an index scan on an IVFFLAT or HNSW index, then has additional data been added to the dataset inbetween queries, or are you varying the search parameters (e.g. `hnsw.ef_search` / `ivfflat.probes`)?

**Comment by lovanto** [comment] 2024-07-08 04:25
@jkatz After run `EXPLAIN ANALYZE` I'm sure it's just run the same query, but the result is still Inconsistent each iteration. Currently using HNSW index created using `CREATE INDEX ON items USING hnsw (embedding vector_l2_ops);` and there's no more search params. Before I'm using pgvector I was in pg_embedding, then migrate to pgvector. Any issue about it? maybe this information can help.

**Comment by ankane** [comment] 2024-07-08 13:59
Hi @lovanto, this looks like a duplicate of #259.

**Closed by ankane** 2024-07-08 13:59 UTC
