### ISSUE TITLE
Memory consumption per connection

### ISSUE THREAD

**Issue by xcu** [pgvector/pgvector#144] opened 2023-06-06 15:39 UTC
Is there an estimation of how much RAM memory could by used by each Postgres connection when using pgvector extensively? For me most of them take ~170MB, and since there are quite a few connections made (around 250) that results in a lot of used memory.

I was wondering if that's sort of expected or whether I am doing something wrong :)

Also, I'm seeing that searches slow down quite a bit during redeploys (from ~1.5s up to 10 in the worst cases). When that happens I guess all the connections to the DB are dropped, but I'm not sure if some shared_buffers might get erased from memory and that causes slow searches for a few minutes? Have you experienced this as well?

**Comment by ankane** [comment] 2023-06-07 05:28
Hi @xcu, I'm not an expert on Postgres memory management, but one reason it could be that high is the value of `work_mem`. Also, for redeploys, one possible cause could be doubling the connections is causing resource contention (using a connection pooler like [PgBouncer](https://www.pgbouncer.org/) in transaction mode could help there, as well as reduce connections in general).

**Comment by xcu** [comment] 2023-06-13 12:27
Hey @ankane , @jkatz , apologies for the late response. I've been sick for the last days :( 

Answering your comments:

- `work_mem` is set to 12MB, so that's around a 7% of the ~170MB that I've seen used per connection. I could try to reduce it, but I guess it's unlikely it will be the responsible for the high memory consumption?
-  Pgbouncer is already in place, but I'm not sure it's in transaction mode. I'll check.
- I'm running `grep ^Pss /proc/<backend_pid>/smaps_rollup` to measure memory usage, since ps and/or top are not great because they contain shared memory. The output looks something like
```
Pss:              736848 kB
Pss_Anon:         274030 kB
Pss_File:             44 kB
Pss_Shmem:        462773 kB
```
- By redeploys I meant application redeploys. The DB is left untouched. When that happens all connections to the DB are dropped and recreated, and during those first ~5mins searches tend to be much slower.

**Comment by ankane** [comment] 2023-06-15 17:07
Hey @xcu, hope you're feeling better. @jkatz might have some more insight on the memory consumption. For redeploys, I'd recommend monitoring the number of connections and other metrics (like CPU, memory, and I/O) to see if anything spikes shortly afterwards.

**Comment by ankane** [comment] 2023-06-30 00:10
Hi @xcu, from [this answer](https://stackoverflow.com/a/65518563), it sounds like high memory usage could be caused by a large number of partitions (https://github.com/pgvector/pgvector/issues/139#issuecomment-1567003097). Going to close this out, but you may want to try https://dba.stackexchange.com/ if that doesn't explain it.

**Closed by ankane** 2023-06-30 00:10 UTC

**Comment by xcu** [comment] 2023-06-30 11:49
That's good to know. There's a decent amount of partitions indeed (getting to 500 soon), so that might explain it. Thanks for the info @ankane !
