### ISSUE TITLE
HNSW Indexing and Filtering

### ISSUE THREAD

**Issue by gkourie** [pgvector/pgvector#575] opened 2024-05-27 19:27 UTC
When using the HNSW index in pgvector, there seems to be an unexpected behavior related to filtering. Specifically, filtering on the HNSW index appears to work, contrary to initial expectations #259 .

test_table:

```
CREATE TABLE test_table (
             document_id INTEGER,
             category_id INTEGER,
             embedding vector,
)
```

hnsw Index creation:

```CREATE INDEX test_table_my_idx ON test_table using hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 128);```

query:

```
EXPLAIN ANALYSE SELECT document_id, min(distance) AS min_dist 
FROM (
    SELECT document_id, (embedding <=> '[-2.5680833, ,.....]') AS distance
    FROM test_table 
    WHERE category_id IN (2220, 1)
    ORDER BY distance
    LIMIT 100
    ) subquery 
GROUP BY document_id
ORDER BY min_dist ASC
LIMIT 3;
```

result:

```
Limit  (cost=169.38..169.39 rows=3 width=12) (actual time=1.678..1.681 rows=3 loops=1)
   ->  Sort  (cost=169.38..169.57 rows=77 width=12) (actual time=1.676..1.678 rows=3 loops=1)
         Sort Key: (min(((test_table.embedding <=> '[-2.5680833,....]'::vector))))
         Sort Method: quicksort  Memory: 25kB
         ->  HashAggregate  (cost=167.61..168.38 rows=77 width=12) (actual time=1.662..1.667 rows=6 loops=1)
               Group Key: test_table.document_id
               Batches: 1  Memory Usage: 24kB
               ->  Limit  (cost=84.60..166.11 rows=100 width=12) (actual time=1.385..1.626 rows=40 loops=1)
                     ->  Index Scan using test_table_my_idx on test_table  (cost=84.60..19367.44 rows=23656 width=12) (actual time=1.384..1.615 rows=40 loops=1)
                           Order By: (embedding <=> '[-2.5680833,....]'::vector)
                           Filter: (category_id = ANY ('{2220,1}'::integer[]))
 Planning Time: 0.802 ms
 Execution Time: 1.885 ms
(13 rows)
```

pgvector version:

```
                             List of installed extensions
  Name   | Version |   Schema   |                     Description                      
---------+---------+------------+------------------------------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
 vector  | 0.7.0   | public     | vector data type and ivfflat and hnsw access methods
```

Index scan is beeing used instead of seq scan. what am i missing here?

**Comment by jkatz** [comment] 2024-05-27 20:52
```
Index Scan using test_table_my_idx on test_table  (cost=84.60..19367.44 rows=23656 width=12) (actual time=1.384..1.615 rows=40 loops=1)
                           Order By: (embedding <=> '[-2.5680833,....]'::vector)
                           Filter: (category_id = ANY ('{2220,1}'::integer[]))
```

This is running as a "post filter" - the index scan occurs first, and tuples that don't match the filter are removed as they're returned from the index.

**Comment by ankane** [comment] 2024-05-27 22:42
This is a duplicate of #259

**Closed by ankane** 2024-05-27 22:42 UTC
